# Generated by Django 2.2 on 2020-06-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200610_0024'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tweet',
            managers=[
            ],
        ),
    ]
